image = [[
    '',
    '                                                                ',
    '                                                                ',
    '                        _-\',                                   ',
    '                     ,-\'   |,                                  ',
    '        V /         |-------|     ,                             ',
    '        \\|| v       |      _ \_--\'|     ,-,                   ',
    '    /   ||/         |     | |     |     |  \__                  ',
    '___V____|_|_____/___|_____|_|_____|_____|_____\____         ____',
    '                                                   ```--````    ',
    '                                ',
    '                                ',
    '                                ',
    'Le monde ne se résume pas à la vie sous la terre.',
    'Dehors la vie a été détruite, plus rien ne bouge et plus rien ',
    'n\'existe.                                ',
],
    [
        '',
        '                                       _-_ ',
        '                                    _-\'   \'-_',
        '                                   |    _    |',
        '    /  \\              ___  |       |   | |   |               ',
        '___V____|_|__________|   |_|_______|___|_|___| ________\\_______',
        '                     |   |                                       ',
        '                     |   |',
        ' ____________________|   |___________',
        '|                                    |',
        '|____________________________________|',
        '',
        '',
        'Pour se sauver vous nous avez donner les plans d\'une ville',
        'sous-terraine. Elle nous a permis de survivre mais personne ne',
        'sais pourquoi le monde est comme ça.',
    ],
    [
        ' _______________________________________________________________ ',
        '|\'-_                                                         _-\'|',
        '|   \'-_                                                   _-\'   |',
        '|      \'-_                                             _-\'      |',
        '|         \'-_                                       _-\'         |',
        '|            \'-_                                 _-\'            |',
        '|               \'-_                           _-\'               |',
        '|                  \'-_______________________-\'                  |',
        '|                                                               |',
        '|                                                               |',
        '|_______________________________________________________________|',
        '',
        'Tu m\'a donné une lettre que je devais te rendre quand tu',
        'reviendra. La voici.',
        '',
        '',
    ],
    [
        'Bonjour,',
        'Oui je suis toi et inversement. J\'ai inventé un engrais super',
        'Efficace. Tu avais quelques doutes sur sa viabilité mais je',
        'voulais sauvé le monde de la famine et baisser le prix de la',
        'nouriture. Tu as oublié un point : n\'avoir qu\'un seul engrais',
        'a permis a une bactérie de se développer sur le monde entier.',
        'Pour se protéger des vecteurs de maladies qui sont tous les',
        'animaux domestiques il est devenu commun de vivre sous terre,',
        'd\'autres ont fait le choix de faire des villes fortifiée.',
        'Un point est commun dans le monde entier : le manque de',
        'nouriture.',
        'Tu t\'en es tellement voulu que t\'es rendu amnésique, je compte',
        'sur le professeur pour pouvoir reprendre place biologiquement.',
        'Tant qu\'il n\'a pas fini sa mission, tu recommenceras ta vie.',
        'Tien prend ça, cela te rendra la mémoire.',
        'C\'est une potion d\'amnésie.',
    ]]

generique = ('Programmé par :',
             'Adrien ROBIN, Jeyani SEBAMALAINANTHAN et Oscar CHEVALIER', '', '',
             'Animations :',
             'Adrien ROBIN', '', '',
             'Personnages :',
             'Jeyani SEBAMALAINATHAN et Oscar CHEVALIER', '', '',
             'Enigmes :',
             'Adrien ROBIN, Jeyani SEBAMALAINANTHAN et Oscar CHEVALIER', '', '',
             'Histoire :',
             'Adrien ROBIN, Jeyani SEBAMALAINATHAN et Oscar CHEVALIER', '', '',
             'Blog :',
             'Jeyani SEBAMALAINATHAN', '', '',
             'Testeurs :',
             'Adrien ROBIN, Jeyani SEBAMALAINANTHAN, Oscar CHEVALIER, Tita',
             'Billy, Billy, Xord, LeProf et Méduse', '', '',
             'Avec l\'aide de :',
             'SINewton et de M. LEBRET', '', '',
             'Inspiré de :',
             'Nethack, Myst 3 et Myst 4', '', '',
             'Idée du générique :',
             'Hideo KOJIMA', '', '',
             'Factengine est Open source.'
             )

logo = (' ||||||| ||||',
        '      ||',
        '  |||||| |||',
        '      ||',
        '      || ||||',
        '   FactEngine')
